window.STORY_DETECTIVE = {
  title: "Fog Over Holborn",
  subtitle: "19th-century London · Detective Jack Harrow and his assistant Clara Vale",
  startNode: "N1",
  endNodes: ["N26", "N27", "N28", "N29", "N30"],
  nodes: [
    { id: "N1", text: `1891 年的 Holborn 被濃霧與煤煙壓得發沉。偵探 Jack Harrow 站在事務所窗邊，手裡夾著失蹤銀行職員 Edwin Mercer 的照片；Clara Vale 則在桌前攤開一封未寫完的信。信上最後一句寫著：『黑色帳本不該被任何人看見。』`, choices: [{ to: "N2", text: "讓 Jack 與 Clara 先檢查信件與私人物品" }, { to: "N3", text: "讓他們前往 Edwin 的住處調查" }, { to: "N4", text: "讓他們直接去銀行詢問同事" }] },
    { id: "N2", text: `Clara 發現信紙邊緣沾著煤灰，還有一絲上流社會香水味。Jack 判斷 Edwin 最近接觸的人不只是銀行同事。`, choices: [{ to: "N5", text: "追查香水來源" }, { to: "N6", text: "分析煤灰可能來自哪一區" }, { to: "N7", text: "檢查火車票與交通紀錄" }] },
    { id: "N3", text: `Edwin 的房間被翻得凌亂，床下藏著一只空文件袋，窗台上留有混著油污的泥痕。這不像普通竊盜，更像有人在找特定文件。`, choices: [{ to: "N6", text: "分析泥土與煤灰" }, { to: "N7", text: "追查 Edwin 最近的交通動線" }, { to: "N8", text: "詢問房東與鄰居" }] },
    { id: "N4", text: `銀行裡人人緊張。出納員透露 Edwin 曾與一名戴灰手套的紳士激烈爭執，內容似乎與保險箱裡的帳冊有關。`, choices: [{ to: "N7", text: "調閱 Edwin 的外出紀錄" }, { to: "N8", text: "盤問員工與守衛" }, { to: "N9", text: "調查灰手套紳士" }] },
    { id: "N5", text: `香味指向 Whitmore 夫人，一位常出入高級旅館的神秘寡婦。旅館女侍說她最近常與一名年輕男子密談。`, choices: [{ to: "N10", text: "追查 Whitmore 夫人的馬車去向" }, { to: "N11", text: "秘密調查她的社交與財務背景" }] },
    { id: "N6", text: `煤灰與泥土都指向城東倉庫區，那裡靠近鐵路與煤場，也常被用作私下交易地點。`, choices: [{ to: "N10", text: "立刻前往倉庫區" }, { to: "N11", text: "先查倉庫租用紀錄" }, { to: "N12", text: "在附近酒館打聽消息" }] },
    { id: "N7", text: `火車票與通勤紀錄都指向 Blackfriars 河岸。Clara 懷疑 Edwin 在夜裡與某人秘密交接。`, choices: [{ to: "N11", text: "調查河岸附近可疑場所" }, { to: "N12", text: "詢問河岸工人" }, { to: "N13", text: "夜裡埋伏觀察" }] },
    { id: "N8", text: `鄰居口供彼此矛盾：有人聽見女人哭聲，有人只看見兩個男人離開。Clara 認為有人刻意混淆時間線。`, choices: [{ to: "N12", text: "拆解矛盾證詞" }, { to: "N13", text: "重建失蹤當晚時間線" }, { to: "N14", text: "尋找可能出現的女人" }] },
    { id: "N9", text: `灰手套紳士名叫 Lionel Ashe，是航運公司的法律顧問，與多名議員和慈善董事都有往來。`, choices: [{ to: "N13", text: "監視 Lionel Ashe" }, { to: "N14", text: "調查他的私人關係" }, { to: "N15", text: "追查他經手的文件" }] },
    { id: "N10", text: `倉庫裡有破碎酒瓶、拖行痕和一枚刻著 E.M. 的帶血袖扣。Edwin 確實曾在這裡遇襲。`, choices: [{ to: "N16", text: "沿拖行痕追查下一地點" }, { to: "N17", text: "把血跡交給法醫檢驗" }] },
    { id: "N11", text: `文件顯示倉庫與 Blackfriars 的私人會所都由同一間空殼公司承租，董事名單裡藏著 Lionel 的假名。`, choices: [{ to: "N16", text: "搜索私人會所" }, { to: "N17", text: "追查空殼公司出資者" }, { to: "N18", text: "整合帳冊與租用資料" }] },
    { id: "N12", text: `河岸工人提到，一名受驚的年輕男子曾被帶上一艘小船，後來又有人花錢要求大家忘記此事。`, choices: [{ to: "N17", text: "追查封口者" }, { to: "N18", text: "比對船隻與帳冊時間" }, { to: "N19", text: "尋找船主" }] },
    { id: "N13", text: `Jack 與 Clara 在河岸看見 Lionel 與 Whitmore 夫人密談。Lionel 把一把小鑰匙交給她。`, choices: [{ to: "N18", text: "跟蹤 Lionel" }, { to: "N19", text: "跟蹤 Whitmore 夫人" }, { to: "N20", text: "設法複製那把鑰匙" }] },
    { id: "N14", text: `Clara 查到 Edwin 的姊姊 Eleanor Mercer 曾任職於慈善基金會，近期突然辭職並消失。`, choices: [{ to: "N19", text: "尋找 Eleanor" }, { to: "N20", text: "調查她離職原因" }, { to: "N21", text: "利用基金會人脈引她現身" }] },
    { id: "N15", text: `法律文件揭露基金會、航運公司與海外空殼帳戶之間的洗錢路徑。Edwin 可能碰到了整套機器的核心。`, choices: [{ to: "N20", text: "潛入基金會地下室" }, { to: "N21", text: "設局逼 Lionel 露出破綻" }, { to: "N22", text: "先把證據交給報社" }] },
    { id: "N16", text: `地下室鐵門後，Edwin 仍活著。他受傷虛弱，卻說帳本還沒全部落入敵人手中。`, choices: [{ to: "N23", text: "先護送 Edwin 到安全屋" }, { to: "N24", text: "立刻追問另一半帳本下落" }, { to: "N25", text: "分頭行動追捕守衛" }] },
    { id: "N17", text: `血跡檢驗證實 Edwin 曾在倉庫遇襲，但不足以致命。有人製造了他已死的假象。`, choices: [{ to: "N24", text: "嘗試立刻逮捕嫌犯" }, { to: "N25", text: "先分散保存證據" }] },
    { id: "N18", text: `所有紀錄拼成完整犯罪鏈：慈善基金、銀行、航運公司與議員共同轉移鉅款。`, choices: [{ to: "N25", text: "公開部分證據" }, { to: "N23", text: "優先保護證人" }, { to: "N24", text: "尋找帳冊正本" }] },
    { id: "N19", text: `Eleanor 終於現身。她交出部分帳頁，並說 Whitmore 夫人可能不是敵人，而是在暗中拖延真正的主使者。`, choices: [{ to: "N23", text: "保護 Eleanor" }, { to: "N24", text: "依線索找帳本正本" }, { to: "N25", text: "利用她在晚宴設局" }] },
    { id: "N20", text: `鑰匙打開暗櫃，裡面有帳冊副本、往來信和一份足以致命的名單。`, choices: [{ to: "N24", text: "尋找正本" }, { to: "N25", text: "把副本分散保存" }] },
    { id: "N21", text: `基金會晚宴上，Lionel 在壓力下承認自己只是代人行事。會場氣氛瞬間凝固。`, choices: [{ to: "N26", text: "當眾揭露證據" }, { to: "N30", text: "讓 Eleanor 出面作證" }] },
    { id: "N22", text: `報社準備在清晨刊出醜聞。編輯提醒：一旦印出去，就再也收不回來。`, choices: [{ to: "N28", text: "立刻印刷特刊" }, { to: "N29", text: "先保護證人再曝光" }] },
    { id: "N23", text: `Edwin 與 Eleanor 被安置到安全屋。你們保住人命，但也給了主使者最後一次逃亡機會。`, choices: [{ to: "N27", text: "清晨前公開所有證據" }, { to: "N30", text: "先抓真正主使者" }] },
    { id: "N24", text: `你們找到帳冊正本、議員署名文件與完整名單。這是能讓整個陰謀崩塌的核心證據。`, choices: [{ to: "N26", text: "帶正本前往警局" }, { to: "N29", text: "先做副本再藏正本" }, { to: "N30", text: "用正本引主使者現身" }] },
    { id: "N25", text: `你們把供詞、密件與副本分散送出。真相第一次不再被任何單一人掌控。`, choices: [{ to: "N27", text: "同步曝光" }, { to: "N28", text: "等待對方犯錯" }, { to: "N29", text: "確保真相穩定公開" }] },
    { id: "N26", text: `結局：Jack 與 Clara 成功救出 Edwin，並保住完整帳冊。基金會與銀行高層遭到拘捕。`, choices: [] },
    { id: "N27", text: `結局：醜聞公開，倫敦政商界震動，但案件變成漫長權力鬥爭。`, choices: [] },
    { id: "N28", text: `結局：Lionel Ashe 逃往歐洲大陸，案件告破大半，但陰影仍未散去。`, choices: [] },
    { id: "N29", text: `結局：你們保住人命與大部分證據，但少數核心人物逃過審判。`, choices: [] },
    { id: "N30", text: `結局：Clara 說服 Eleanor 出庭，整個陰謀徹底崩解。Clara 也成為倫敦最敏銳的調查者之一。`, choices: [] }
  ]
};
